name: Automated Scans
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk-sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Setup Java (Maven)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Build project to resolve dependencies
      - name: Build with Maven
        run: mvn clean install -DskipTests
      
      # Snyk SCA for Java (Maven)
      - name: Run Snyk Security Scan
        uses: snyk/actions/maven@master
        with:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          args: --fail-on=upgradable --scan-all-unmanaged

  sonarcloud-sast:
    runs-on: ubuntu-latest
    needs: [snyk-sca]  # Wait for SCA first
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # SonarCloud analysis for Java
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  zap-dast:
    runs-on: ubuntu-latest
    needs: [sonarcloud-sast]  # Run after SAST
    if: github.event_name == 'push'  # Only run on push (not PR)
    steps:
      - uses: actions/checkout@v3
      
      # Start Spring Boot app (adjust for your framework)
      - name: Start Java server
        run: |
          mvn spring-boot:run &
          sleep 120  # Wait for app to start
          curl --retry 5 http://localhost:8080/actuator/health
      
      # OWASP ZAP DAST scan
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.6.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-a -j'  # Active scan + JSON report
      
      # Upload report as artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-results
          path: zap-report.json