name: Snyk SCA Scan
on: [push, pull_request]

jobs:
  snyk-sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Setup Node.js (adjust for Python/Java/etc.)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      # Install dependencies (required for Snyk to scan)
      - run: npm install
      
      # Run Snyk Open Source Scan
      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        with:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          args: --fail-on=upgradable  # Fails if critical vulns found